### ISSUE TITLE
Use a physically meaningful X-axis (i.e. wavelength)

### ISSUE THREAD

**Issue by aloboa** [DHI-GRAS/Temporal_profile_tool#9]
Visualizing spectra by band number can be very misleading.
Could you consider the option of reading a file with 2 columns (band, wavelength)
and using that information to display wavelength in the x-axis?

**Comment by radosuav** [comment]
Thanks for the suggestion. The x-axis is the next thing that I want to look at and I will take your idea and #7 into consideration.

**Comment by aloboa** [comment]
In few image format cases, wavelength (or time, as pointed by #7) information is available for raster bands. For example, envi *.hdr files have a field for wavelength and another for band names. For example,
wavelength = {
  0.485000,  0.560000,  0.660000,  0.830000,  1.650000, 11.400000,  2.215000}
in the case of Landsat TM.
(See http://www.harrisgeospatial.com/docs/ENVIHeaderFiles.html)
In that case the 2 column file that I suggest might not be needed, but note that the wavelength field is actually optional in the *.hdr file

**Comment by aloboa** [comment]
Radoslaw,
Any progress on this issue and #7?
Thanks

**Comment by radosuav** [comment]
Unfortunately nothing yet. I hope to find some time to work on this around May.

**Comment by aloboa** [comment]
Radoslaw,
Have you been able to find some time for this issue?
Thanks
